name: animated_styled_widget
description: Lets you use a serializable style to make customizable and animated widgets.
version: 0.4.6
homepage: https://github.com/KevinVan720/animated_styled_widget

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

  dimension: ^0.1.6

  flutter_class_parser: ^0.2.4

  morphable_shape:
    git:
      url: https://github.com/antonzk/morphable_shape.git
      ref: main

  tuple: ^2.0.0

  provider: ^6.0.0

  simple_animations: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

